#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=16gb,walltime=02:00:00
#PBS -N bl.bem

#SBATCH --ntasks-per-node=1
#SBATCH --mem=16G
#SBATCH --time=02:00:00

set -e
set -x

if [ -n "$FREESURFER_LICENSE" ]; then
    echo $FREESURFER_LICENSE > license.txt
elif [ -n "$FS_LICENSE" ] && [ -f "$FS_LICENSE" ]; then
    cp "$FS_LICENSE" license.txt
else
    echo "Please set FREESURFER_LICENSE or FS_LICENSE in resource environment" && exit 1
fi

echo "=== LICENSE DEBUG ==="
echo "FREESURFER_LICENSE: $FREESURFER_LICENSE"
echo "FS_LICENSE: $FS_LICENSE"
echo "license.txt content:"; cat license.txt
echo "FS_LICENSE file content:"; cat "$FS_LICENSE"
echo "FREESURFER_LICENSE file content:"; cat "$FREESURFER_LICENSE"
echo "===================="


singularity exec \
  -B `pwd`/license.txt:/opt/freesurfer/license.txt \
  docker://brainlife/mne-freesurfer:7.3.2-1.2.1 \
  python3 main.py
