#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=16gb,walltime=02:00:00
#PBS -N bl.bem

#SBATCH --ntasks-per-node=1
#SBATCH --mem=16G
#SBATCH --time=02:00:00

set -e
set -x

if [ -n "$FS_LICENSE" ] && [ -f "$FS_LICENSE" ]; then
    cp "$FS_LICENSE" license.txt
elif [ -n "$FREESURFER_LICENSE" ]; then
    echo $FREESURFER_LICENSE > license.txt
else
    echo "Please set FREESURFER_LICENSE or FS_LICENSE in resource environment" && exit 1
fi

FS_PATH=$(jq -r '.freesurfer // .output' config.json)
FS_PATH=$(realpath "$FS_PATH")

mkdir -p out_dir

singularity exec \
  -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
  docker://brainlife/freesurfer:7.1.1 \
  bash ./watershed_test.sh $FS_PATH
